# Generated by Django 3.0.1 on 2020-05-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_models', '0003_author_book_publisher_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
