# Generated by Django 3.0.1 on 2020-05-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_models', '0004_auto_20200518_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='headshot',
            field=models.FileField(upload_to=''),
        ),
    ]
