# Generated by Django 3.0.1 on 2020-06-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_models', '0005_auto_20200518_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='headshot',
            field=models.FileField(help_text='Please upload photo. (jpg, jpeg, png)', upload_to=''),
        ),
    ]
